# Generated by Django 3.1.2 on 2020-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_name', models.CharField(max_length=50)),
                ('Category', models.CharField(default='', max_length=50)),
                ('SubCategory', models.CharField(default='', max_length=50)),
                ('Price', models.IntegerField(default=0)),
                ('Desc', models.CharField(default='', max_length=50)),
                ('Date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
    ]
