# Generated by Django 3.1.2 on 2020-12-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201213_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Desc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
