# Generated by Django 3.1.2 on 2020-12-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201220_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='dat',
            new_name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
